# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: "Clean the {{ ansible_facts['distribution'] }} guest operating system."
  include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Debian']
